version: '3'

services:
  nginx:
    image: nginx:stable
    container_name: wordpress-nginx
    ports:
       - '${NGINX_HOST_PORT}:80'
    volumes:
       - ./nginx:/etc/nginx/conf.d
       - ./logs/nginx:/var/log/nginx
       - ./wordpress:/var/www/html
    restart: always
    environment:
       TZ: Asia/Tokyo
    depends_on:
       - wordpress

  mariadb:
    image: mariadb:latest
    container_name: wordpress-mariadb
    ports:
       - '3306'
    volumes:
       - ./db-data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       TZ: Asia/Tokyo

  wordpress:
    image: wordpress:fpm
    container_name: wordpress
    expose:
       - '9000'
    volumes:
       - ./wordpress:/var/www/html
       - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
    environment:
       WORDPRESS_DB_HOST: wordpress-mariadb
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
       WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
       TZ: Asia/Tokyo
    depends_on:
       - mariadb
    links:
       - mariadb