version: "3"
services:
  nginx:
    image: nginx:1.19.6
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/log:/var/log/nginx"
      - "./wordpress:/var/www/html"
    ports:
      - "${NGINX_HOST_PORT}:80"
    depends_on:
      - wordpress
    restart: always
    container_name: nginx
  wordpress:
    image: wordpress:5.6-php7.4-fpm
    depends_on:
      - db
    volumes:
      - "./wordpress:/var/www/html"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    container_name: wordpress
  db:
    image: mariadb:10.5.8
    restart: always
    volumes:
      - "./db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    container_name: db
volumes:
    db: